
-- Queries da tabela de itens das propostas
CREATE TABLE tb_itens_propostas(
id_item_proposta INT NOT NULL AUTO_INCREMENT,
data_insercao DATETIME NOT NULL,
id_usuario INT,
id_status INT NOT NULL,
id_proposta INT NOT NULL,
id_status_aprovacao INT,
id_justificativa_aprovacao INT,
id_tipo_item INT,
id_conjunto INT,
id_especificacao INT,
id_fornecedor INT,
codigo_item VARCHAR(255),
descricao_item TEXT,
quantidade_item DECIMAL(20, 2),
preco_unitario_inicial_item DECIMAL(20, 2),
percentual_ipi_item DECIMAL(20, 10),
percentual_icms_item DECIMAL(20, 10),
ncm_item VARCHAR(30),
mva_item DECIMAL(20, 10),
valor_st_item DECIMAL(20, 2),
valor_total_inicial_item DECIMAL(20, 2),
prazo_inicial_item VARCHAR(255),
frete_unitario_item DECIMAL(20, 2),
desconto_inicial_item DECIMAL(20, 10),
id_tipo_substituicao_tributaria_item INT,
id_origem_item INT,
preco_apos_desconto_inicial_item DECIMAL(20, 2),
preco_com_ipi_e_icms_item DECIMAL(20, 2),
percentual_aliquota_externa_icms_item DECIMAL(20, 10),
valor_icms_credito_item DECIMAL(20, 2),
percentual_mva_item DECIMAL(20, 10),
valor_mva_item DECIMAL(20, 2),
preco_com_mva_item DECIMAL(20, 2),
percentual_aliquota_interna_icms_item DECIMAL(20, 10),
valor_icms_debito_item DECIMAL(20, 2),
saldo_icms_item DECIMAL(20, 2),
preco_unitario_para_revendedor_item DECIMAL(20, 2),
impostos_federais_item DECIMAL(20, 10),
rateio_despesa_fixa_item DECIMAL(20, 10),
percentual_lucro_necessario_item DECIMAL(20, 10),
preco_lista_venda_item DECIMAL(20, 2),
desconto_final_item DECIMAL(20, 10),
preco_unitario_final_item DECIMAL(20, 2),
preco_total_final_item DECIMAL(20, 2),
quantidade_estoque_codigo_completo_item DECIMAL(20, 2),
quantidade_estoque_codigo_abreviado_item DECIMAL(20, 2),
informacao_estoque_codigo_completo_item VARCHAR(255),
informacao_estoque_codigo_abreviado_item VARCHAR(255),
prazo_final_item VARCHAR(255),
comentarios_item TEXT,
data_aprovacao_item DATETIME,
data_edicao_item DATETIME,
PRIMARY KEY (id_item_proposta),
FOREIGN KEY (id_usuario) REFERENCES tb_usuarios (id_usuario),
FOREIGN KEY (id_status) REFERENCES tb_status (id_status),
FOREIGN KEY (id_proposta) REFERENCES tb_propostas (id_proposta),
FOREIGN KEY (id_status_aprovacao) REFERENCES tb_status_aprovacao (id_status_aprovacao),
FOREIGN KEY (id_justificativa_aprovacao) REFERENCES tb_justificativas_aprovacao (id_justificativa_aprovacao),
FOREIGN KEY (id_tipo_item) REFERENCES tb_tipos_item (id_tipo_item),
FOREIGN KEY (id_conjunto) REFERENCES tb_conjuntos (id_conjunto),
FOREIGN KEY (id_especificacao) REFERENCES tb_especificacoes (id_especificacao),
FOREIGN KEY (id_fornecedor) REFERENCES tb_fornecedores (id_fornecedor),
FOREIGN KEY (id_tipo_substituicao_tributaria_item) REFERENCES tb_tipos_substituicao_tributaria (id_tipo_substituicao_tributaria),
FOREIGN KEY (id_origem_item) REFERENCES tb_origens (id_origem)
);

DELIMITER $$
CREATE PROCEDURE sp_inserir_item_proposta(
IN p_data_insercao DATETIME,
IN p_id_usuario INT,  
IN p_id_status INT,
IN p_id_proposta INT,
IN p_id_status_aprovacao INT,
IN p_id_justificativa_aprovacao INT,
IN p_id_tipo_item INT,
IN p_id_conjunto INT,
IN p_id_especificacao INT,
IN p_id_fornecedor INT,
IN p_codigo_item VARCHAR(255),
IN p_descricao_item TEXT,
IN p_quantidade_item DECIMAL(20, 2),
IN p_preco_unitario_inicial_item DECIMAL(20, 2),
IN p_percentual_ipi_item DECIMAL(20, 10),
IN p_percentual_icms_item DECIMAL(20, 10),
IN p_ncm_item VARCHAR(30),
IN p_mva_item DECIMAL(20, 10),
IN p_valor_st_item DECIMAL(20, 2),
IN p_valor_total_inicial_item DECIMAL(20, 2),
IN p_prazo_inicial_item VARCHAR(255),
IN p_frete_unitario_item DECIMAL(20, 2),
IN p_desconto_inicial_item DECIMAL(20, 10),
IN p_id_tipo_substituicao_tributaria_item INT,
IN p_id_origem_item INT,
IN p_preco_apos_desconto_inicial_item DECIMAL(20, 2),
IN p_preco_com_ipi_e_icms_item DECIMAL(20, 2),
IN p_percentual_aliquota_externa_icms_item DECIMAL(20, 10),
IN p_valor_icms_credito_item DECIMAL(20, 2),
IN p_percentual_mva_item DECIMAL(20, 10),
IN p_valor_mva_item DECIMAL(20, 2),
IN p_preco_com_mva_item DECIMAL(20, 2),
IN p_percentual_aliquota_interna_icms_item DECIMAL(20, 10),
IN p_valor_icms_debito_item DECIMAL(20, 2),
IN p_saldo_icms_item DECIMAL(20, 2),
IN p_preco_unitario_para_revendedor_item DECIMAL(20, 2),
IN p_impostos_federais_item DECIMAL(20, 10),
IN p_rateio_despesa_fixa_item DECIMAL(20, 10),
IN p_percentual_lucro_necessario_item DECIMAL(20, 10),
IN p_preco_lista_venda_item DECIMAL(20, 2),
IN p_desconto_final_item DECIMAL(20, 10),
IN p_preco_unitario_final_item DECIMAL(20, 2),
IN p_preco_total_final_item DECIMAL(20, 2),
IN p_quantidade_estoque_codigo_completo_item DECIMAL(20, 2),
IN p_quantidade_estoque_codigo_abreviado_item DECIMAL(20, 2),
IN p_informacao_estoque_codigo_completo_item VARCHAR(255),
IN p_informacao_estoque_codigo_abreviado_item VARCHAR(255),
IN p_prazo_final_item VARCHAR(255),
IN p_comentarios_item TEXT,
IN p_data_aprovacao_item DATETIME,
OUT p_mensagem VARCHAR(255))
BEGIN
INSERT INTO tb_itens_propostas 
(data_insercao,
id_usuario, 
id_status,
id_proposta,
id_status_aprovacao,
id_justificativa_aprovacao,
id_tipo_item,
id_conjunto,
id_especificacao,
id_fornecedor,
codigo_item,
descricao_item,
quantidade_item,
preco_unitario_inicial_item,
percentual_ipi_item,
percentual_icms_item,
ncm_item,
mva_item,
valor_st_item,
valor_total_inicial_item,
prazo_inicial_item,
frete_unitario_item,
desconto_inicial_item,
id_tipo_substituicao_tributaria_item,
id_origem_item,
preco_apos_desconto_inicial_item,
preco_com_ipi_e_icms_item,
percentual_aliquota_externa_icms_item,
valor_icms_credito_item,
percentual_mva_item,
valor_mva_item,
preco_com_mva_item,
percentual_aliquota_interna_icms_item,
valor_icms_debito_item,
saldo_icms_item,
preco_unitario_para_revendedor_item,
impostos_federais_item,
rateio_despesa_fixa_item,
percentual_lucro_necessario_item,
preco_lista_venda_item,
desconto_final_item,
preco_unitario_final_item,
preco_total_final_item,
quantidade_estoque_codigo_completo_item,
quantidade_estoque_codigo_abreviado_item,
informacao_estoque_codigo_completo_item,
informacao_estoque_codigo_abreviado_item,
prazo_final_item,
comentarios_item,
data_aprovacao_item) 
VALUES 
(p_data_insercao,
p_id_usuario, 
p_id_status,
p_id_proposta,
p_id_status_aprovacao,
p_id_justificativa_aprovacao,
p_id_tipo_item,
p_id_conjunto,
p_id_especificacao,
p_id_fornecedor,
p_codigo_item,
p_descricao_item,
p_quantidade_item,
p_preco_unitario_inicial_item,
p_percentual_ipi_item,
p_percentual_icms_item,
p_ncm_item,
p_mva_item,
p_valor_st_item,
p_valor_total_inicial_item,
p_prazo_inicial_item,
p_frete_unitario_item,
p_desconto_inicial_item,
p_id_tipo_substituicao_tributaria_item,
p_id_origem_item,
p_preco_apos_desconto_inicial_item,
p_preco_com_ipi_e_icms_item,
p_percentual_aliquota_externa_icms_item,
p_valor_icms_credito_item,
p_percentual_mva_item,
p_valor_mva_item,
p_preco_com_mva_item,
p_percentual_aliquota_interna_icms_item,
p_valor_icms_debito_item,
p_saldo_icms_item,
p_preco_unitario_para_revendedor_item,
p_impostos_federais_item,
p_rateio_despesa_fixa_item,
p_percentual_lucro_necessario_item,
p_preco_lista_venda_item,
p_desconto_final_item,
p_preco_unitario_final_item,
p_preco_total_final_item,
p_quantidade_estoque_codigo_completo_item,
p_quantidade_estoque_codigo_abreviado_item,
p_informacao_estoque_codigo_completo_item,
p_informacao_estoque_codigo_abreviado_item,
p_prazo_final_item,
p_comentarios_item,
p_data_aprovacao_item);
SET p_mensagem='Valor inserido com sucesso';
END$$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE sp_editar_item_proposta(
IN p_id_item_proposta INT,
IN p_id_status INT,
IN p_id_proposta INT,
IN p_id_status_aprovacao INT,
IN p_id_justificativa_aprovacao INT,
IN p_id_tipo_item INT,
IN p_id_conjunto INT,
IN p_id_especificacao INT,
IN p_id_fornecedor INT,
IN p_codigo_item VARCHAR(255),
IN p_descricao_item TEXT,
IN p_quantidade_item DECIMAL(20, 2),
IN p_preco_unitario_inicial_item DECIMAL(20, 2),
IN p_percentual_ipi_item DECIMAL(20, 10),
IN p_percentual_icms_item DECIMAL(20, 10),
IN p_ncm_item VARCHAR(30),
IN p_mva_item DECIMAL(20, 10),
IN p_valor_st_item DECIMAL(20, 2),
IN p_valor_total_inicial_item DECIMAL(20, 2),
IN p_prazo_inicial_item VARCHAR(255),
IN p_frete_unitario_item DECIMAL(20, 2),
IN p_desconto_inicial_item DECIMAL(20, 10),
IN p_id_tipo_substituicao_tributaria_item INT,
IN p_id_origem_item INT,
IN p_preco_apos_desconto_inicial_item DECIMAL(20, 2),
IN p_preco_com_ipi_e_icms_item DECIMAL(20, 2),
IN p_percentual_aliquota_externa_icms_item DECIMAL(20, 10),
IN p_valor_icms_credito_item DECIMAL(20, 2),
IN p_percentual_mva_item DECIMAL(20, 10),
IN p_valor_mva_item DECIMAL(20, 2),
IN p_preco_com_mva_item DECIMAL(20, 2),
IN p_percentual_aliquota_interna_icms_item DECIMAL(20, 10),
IN p_valor_icms_debito_item DECIMAL(20, 2),
IN p_saldo_icms_item DECIMAL(20, 2),
IN p_preco_unitario_para_revendedor_item DECIMAL(20, 2),
IN p_impostos_federais_item DECIMAL(20, 10),
IN p_rateio_despesa_fixa_item DECIMAL(20, 10),
IN p_percentual_lucro_necessario_item DECIMAL(20, 10),
IN p_preco_lista_venda_item DECIMAL(20, 2),
IN p_desconto_final_item DECIMAL(20, 10),
IN p_preco_unitario_final_item DECIMAL(20, 2),
IN p_preco_total_final_item DECIMAL(20, 2),
IN p_quantidade_estoque_codigo_completo_item DECIMAL(20, 2),
IN p_quantidade_estoque_codigo_abreviado_item DECIMAL(20, 2),
IN p_informacao_estoque_codigo_completo_item VARCHAR(255),
IN p_informacao_estoque_codigo_abreviado_item VARCHAR(255),
IN p_prazo_final_item VARCHAR(255),
IN p_comentarios_item TEXT,
IN p_data_aprovacao_item DATETIME,
IN p_data_edicao_item DATETIME,
OUT p_mensagem VARCHAR(255))
BEGIN
IF(NOT(EXISTS(SELECT * FROM tb_itens_propostas WHERE id_item_proposta=p_id_item_proposta))) THEN
SET p_mensagem='Valor não existe';
ELSE
UPDATE tb_itens_propostas SET 
id_status = p_id_status,
id_proposta = p_id_proposta,
id_status_aprovacao = p_id_status_aprovacao,
id_justificativa_aprovacao = p_id_justificativa_aprovacao,
id_tipo_item = p_id_tipo_item,
id_conjunto = p_id_conjunto,
id_especificacao = p_id_especificacao,
id_fornecedor = p_id_fornecedor,
codigo_item = p_codigo_item,
descricao_item = p_descricao_item,
quantidade_item = p_quantidade_item,
preco_unitario_inicial_item = p_preco_unitario_inicial_item,
percentual_ipi_item = p_percentual_ipi_item,
percentual_icms_item = p_percentual_icms_item,
ncm_item = p_ncm_item,
mva_item = p_mva_item,
valor_st_item = p_valor_st_item,
valor_total_inicial_item = p_valor_total_inicial_item,
prazo_inicial_item = p_prazo_inicial_item,
frete_unitario_item = p_frete_unitario_item,
desconto_inicial_item = p_desconto_inicial_item,
id_tipo_substituicao_tributaria_item = p_id_tipo_substituicao_tributaria_item,
id_origem_item = p_id_origem_item,
preco_apos_desconto_inicial_item = p_preco_apos_desconto_inicial_item,
preco_com_ipi_e_icms_item = p_preco_com_ipi_e_icms_item,
percentual_aliquota_externa_icms_item = p_percentual_aliquota_externa_icms_item,
valor_icms_credito_item = p_valor_icms_credito_item,
percentual_mva_item = p_percentual_mva_item,
valor_mva_item = p_valor_mva_item,
preco_com_mva_item = p_preco_com_mva_item,
percentual_aliquota_interna_icms_item = p_percentual_aliquota_interna_icms_item,
valor_icms_debito_item = p_valor_icms_debito_item,
saldo_icms_item = p_saldo_icms_item,
preco_unitario_para_revendedor_item = p_preco_unitario_para_revendedor_item,
impostos_federais_item = p_impostos_federais_item,
rateio_despesa_fixa_item = p_rateio_despesa_fixa_item,
percentual_lucro_necessario_item = p_percentual_lucro_necessario_item,
preco_lista_venda_item = p_preco_lista_venda_item,
desconto_final_item = p_desconto_final_item,
preco_unitario_final_item = p_preco_unitario_final_item,
preco_total_final_item = p_preco_total_final_item,
quantidade_estoque_codigo_completo_item = p_quantidade_estoque_codigo_completo_item,
quantidade_estoque_codigo_abreviado_item = p_quantidade_estoque_codigo_abreviado_item,
informacao_estoque_codigo_completo_item = p_informacao_estoque_codigo_completo_item,
informacao_estoque_codigo_abreviado_item = p_informacao_estoque_codigo_abreviado_item,
prazo_final_item = p_prazo_final_item,
comentarios_item = p_comentarios_item,
data_aprovacao_item = p_data_aprovacao_item,
data_edicao_item = p_data_edicao_item
WHERE id_item_proposta=p_id_item_proposta;
SET p_mensagem='Valor editado com sucesso';
END IF;
END$$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE sp_excluir_item_proposta(
IN p_id_item_proposta INT,
OUT p_mensagem VARCHAR(255))
BEGIN
IF(NOT(EXISTS(SELECT * FROM tb_itens_propostas WHERE id_item_proposta=p_id_item_proposta))) THEN
SET p_mensagem='Valor não existe';
ELSE
DELETE FROM tb_itens_propostas
WHERE id_item_proposta=p_id_item_proposta;
SET p_mensagem='Valor excluído com sucesso';
END IF;
END$$
DELIMITER ;